# $SITE = https://api-billing.advancedhosting.com
# $HIAM = https://sol-beta-id.advancedhosting.com
# $token = 1f9045b1e6671e924a7ac6d1e6aefb3086260785
XDEBUG_SESSION_START=session_name

# User info
GET $HIAM/userinfo
Authorization: Bearer $token

# Bills search
GET $SITE/BillsSearch
Authorization: Bearer $token

# calc cert
POST $SITE/actionsCalcValue
Authorization: Bearer $token
1[product_id]=10487690
1[object]=certificate
1[type]=certificate_purchase
1[amount]=2
1[calculation_id]=777

# domain+cert
POST $SITE/actionsCalcValue
Authorization: Bearer $token
0[object]=domain
0[type]=registration
0[amount]=1
0[domain]=asdfasfsd.com
0[product_id]=1000212
0[calculation_id]=999
1[product_id]=10487690
1[object]=certificate
1[type]=certificate_purchase
1[amount]=2
1[calculation_id]=777
2[product_id]=10515201
2[object_id]=123
2[object]=certificate
2[type]=certificate_renewal
2[amount]=2
2[calculation_id]=555

POST $SITE/actionsCalcValue
Authorization: Bearer $token
3[id]=15958755
3[object]=certificate
3[product_id]=10888670
3[type]=certificate_renewal
3[amount]=1
3[calculation_id]=333

POST $SITE/certificatePurchase
Authorization: Bearer $token
product_id=10487690
amount=2

POST $SITE/actionsCalcValue
Authorization: Bearer $token
0[type]=premium_dns_purchase
0[object]=feature
0[domain]=solex.kiev.ua
0[amount]=2

POST $SITE/actionCalcValue
Authorization: Bearer $token
type=premium_dns_purchase
object=feature
domain=solex.kiev.ua
amount=2
